#!/bin/sh

#Author: Rodrigo Mayorga Vallejos <rmayorgav@gmail.com>

# validate root user
if [ $(id -u) -ne 0 ]; then
    echo You are not root!
    exit 1
fi

apt-get update && apt-get upgrade -y  && apt-get autoremove -y

