#!/bin/bash

#Author: Rodrigo Mayorga Vallejos <rmayorgav@gmail.com>

# validate root user
if [ $(id --user) -ne 0 ]; then
    echo You are not root!
    exit 1
fi

# get updates
apt update -y

for opt in $@; do
    case $opt in
        "man-pages")
            apt install -y man-db
            ;;
        "gnupg")
            apt install -y gnupg
            ;;
        "editors")
            apt install -y vim neovim mc nano
            ;;
        "c-devel")
            apt install -y build-essential clang git cmake gdb automake autoconf
            ;;
        "php")
            apt install -y php-cli php-curl php-gd php-dompdf php-zip 
            ;;
        "python")
            apt install -y python3 python3-dev python3-venv python3-pip python-is-python3
            ;;
        "mingw")
            apt install -y mingw-w64
            ;;
        "monitors")
            apt install -y htop iftop
            ;;
        "dotnet")
            wget https://dot.net/v1/dotnet-install.sh -O /tmp/dotnet-install.sh
            chmod +x /tmp/dotnet-install.sh
            /tmp/dotnet-install.sh --version latest
            ;;
        "nodejs")
            apt install -y curl
			apt-get update
			apt-get install -y ca-certificates curl gnupg
			mkdir -p /etc/apt/keyrings
			curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
			NODE_MAJOR=20
			echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list
            apt-get update
            apt-get install -y nodejs
            ;;
        *)
            echo "Opción $opt no válida"
            ;;
    esac
done

