#!/bin/sh

#Author: Rodrigo Mayorga Vallejos <rmayorgav@gmail.com>

# validate root user
if [ $(id -u) -ne 0 ]; then
    echo You are not root!
    exit 1
fi

apt update && apt upgrade -y  && apt autoremove -y
