#!/bin/bash

#Author: Rodrigo Mayorga Vallejos <rmayorgav@gmail.com>

# validate root user
if [ $(id --user) -ne 0 ]; then
    echo You are not root!
    exit 1
fi

# get updates
apt update -y

for opt in $@; do
    case $opt in
        "--man-page")
            apt install -y man-db
            ;;
        "--gnupg")
            apt install -y gnupg
            ;;
        "--editors")
            apt install -y vim neovim mc nano
            ;;
        "--c-devel")
            apt install -y build-essential clang git cmake gdb automake autoconf
            ;;
        "--python3")
            apt install -y python3 python3-dev python3-venv python3-pip
            ;;
        "--mingw")
            apt install -y mingw-w64
            ;;
        "--monitors")
            apt install -y htop iftop
            ;;
        "--nodejs-lts")
            apt install -y curl
            curl -fsSL https://deb.nodesource.com/setup_lts.x | bash - && apt install -y nodejs
            ;;
        *)
            echo "Opción $opt no válida"
            ;;
    esac
done

