#!/bin/sh

#Author: Rodrigo Mayorga Vallejos <rmayorgav@gmail.com>

# validate root user
if [ $(id -u) -ne 0 ]; then
    echo You are not root!
    exit 1
fi

# get updates
apt-get update -y

for opt in $@; do
    case $opt in
        "man-pages")
            apt-get install -y man-db
            ;;
        "gnupg")
            apt-get install -y gnupg gnupg2
            ;;
        "editors")
            apt-get install -y vim neovim mc nano
            ;;
        "c-devel")
            apt-get install -y build-essential clang git cmake gdb automake autoconf
            ;;
        "php")
            apt-get install -y php-cli php-curl php-gd php-dompdf php-zip 
            ;;
        "python")
            apt-get install -y python3 python3-dev python3-venv python3-pip python-is-python3
            ;;
        "mingw")
            apt-get install -y mingw-w64
            ;;
        "monitors")
            apt-get install -y htop iftop
            ;;
        "nodejs")
            apt-get install -y curl
			apt-get-get update
			apt-get-get install -y ca-certificates curl gnupg
			mkdir -p /etc/apt-get/keyrings
			curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt-get/keyrings/nodesource.gpg
			NODE_MAJOR=20
			echo "deb [signed-by=/etc/apt-get/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | sudo tee /etc/apt-get/sources.list.d/nodesource.list
            apt-get-get update
            apt-get-get install -y nodejs
            ;;
        *)
            echo "Opción $opt no válida"
            ;;
    esac
done
