#!/bin/bash

#Author: Rodrigo Mayorga Vallejos <rmayorgav@gmail.com>
wget https://dot.net/v1/dotnet-install.sh -O /tmp/dotnet-install.sh
chmod +x /tmp/dotnet-install.sh
/tmp/dotnet-install.sh --version latest